In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
arr = np.array([0,1,2,3,4,5])
for i in arr:
  print(arr[i])
  i += 1

0
1
2
3
4
5


In [27]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[1:10])

[1 2 3 4 5 6 7 8 9]


In [28]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr.dtype)

int64


In [29]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10], dtype = "S")
print(arr)
print(arr.dtype)

[b'0' b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']
|S2


In [35]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr.shape)

(2, 5)


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [45]:
arr1 = np.array([0,1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([11,12,13,14,15,16,17,18,19,20])
arr = np.concatenate((arr1, arr2))
print(arr1)
print()
print(arr2)
print()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]

[11 12 13 14 15 16 17 18 19 20]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [47]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
np.where(arr == 8)

(array([8]),)


In [71]:
ran = np.random.randint(1000000000000000000)
print(ran)

235363915694266383


In [72]:
arr1 = np.array([10,123,5,7,78,4,52,353,2,43,24,56])
print(np.sort(arr1))

[  2   4   5   7  10  24  43  52  56  78 123 353]


In [82]:
a = np.arange(9, dtype = np.float64).reshape(3,3)
print("First array:")
print(a)

b = np.array([10,10,10])
print("Second array:")
print(b)

add = np.add(a,b)
print("Addition:")
print(add)

substract = np.subtract(a,b)
print("Substract:")
print(substract)

multiply = np.multiply(a,b)
print("Multiplication:")
print(multiply)

divide = np.divide(a,b)
print("Divide:")
print(divide)

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Second array:
[10 10 10]
Addition:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
Substract:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
Multiplication:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
Divide:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [73]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [76]:
arr = np.arange(5,10)
print(arr)

[5 6 7 8 9]


In [77]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [79]:
arr = np.arange(0,1,0.2, dtype = np.float64)
print(arr)

[0.  0.2 0.4 0.6 0.8]


In [83]:
data_type = [("name", "S15"), ("class", "int"), ("height", "float")]
student_details = [("James", 5, 50.5), ("Brian", 6, 60.2), ("Hawk", 7, 75.7)]
arr = np.array(student_details, dtype = data_type)
print("Original array:")
print(student_details)
print("Sorted by height:")
print(np.sort(arr, order = "height"))

Original array:
[('James', 5, 50.5), ('Brian', 6, 60.2), ('Hawk', 7, 75.7)]
Sorted by height:
[(b'James', 5, 50.5) (b'Brian', 6, 60.2) (b'Hawk', 7, 75.7)]
